"""Initial migration.

Revision ID: 675ec149348a
Revises: 9e21fdc0ed09
Create Date: 2023-10-20 17:26:39.203524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675ec149348a'
down_revision = '9e21fdc0ed09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PasswordManager', schema=None) as batch_op:
        batch_op.alter_column('site_password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PasswordManager', schema=None) as batch_op:
        batch_op.alter_column('site_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
